name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - name: Remove unwanted to provide more disk space
      # https://github.com/marketplace/actions/maximize-build-disk-space
      # https://github.com/actions/runner-images/issues/2840
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /opt/ghc
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"

    - uses: actions/checkout@v3

    - name: Install dependencies
      run: make install

    - name: Create Tesseract models
      run: make all-tess
      
    - name: Create Hunspell dict
      run: make all-hunspell
      
    - uses: maxmilton/action-create-release@v0
      with:
        files: |
          *_dta*.traineddata
          de-dta.*
        git-tag: ${{ github.ref }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
  
